CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Categories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Depth" text NOT NULL,
    "Slug" text NOT NULL,
    "Path" text NOT NULL,
    CONSTRAINT "PK_Categories" PRIMARY KEY ("Id")
);

CREATE TABLE "Products" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text COLLATE tr_icu_det NOT NULL,
    "Description" text,
    "Price" numeric NOT NULL,
    "Rating" real NOT NULL,
    "ExtraAmount" integer NOT NULL,
    "ImageUrl" text,
    "DocumentUrl" text,
    "Slug" text,
    CONSTRAINT "PK_Products" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserName" text,
    "Email" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "Inventories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProductId" integer NOT NULL,
    "Quantity" integer NOT NULL,
    "LastUpdated" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Inventories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Inventories_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ProductCategories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProductId" integer NOT NULL,
    "CategoryId" integer NOT NULL,
    CONSTRAINT "PK_ProductCategories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ProductCategories_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ProductCategories_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ProductDiscounts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProductId" integer NOT NULL,
    "DiscountPercentage" numeric NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_ProductDiscounts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ProductDiscounts_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Addresses" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Title" character varying(128) NOT NULL,
    "Name" character varying(128) NOT NULL,
    "Surname" character varying(128) NOT NULL,
    "PhoneNumber" character varying(32) NOT NULL,
    "FullAddress" character varying(512) NOT NULL,
    "City" character varying(128) NOT NULL,
    "State" character varying(128) NOT NULL,
    "Neighbourhood" character varying(256) NOT NULL,
    "IsDefault" boolean NOT NULL,
    CONSTRAINT "PK_Addresses" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Addresses_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Carts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer,
    "AnonId" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Carts" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_Cart_Owner" CHECK (("UserId" IS NOT NULL AND "AnonId" IS NULL) OR ("UserId" IS NULL AND "AnonId" IS NOT NULL)),
    CONSTRAINT "FK_Carts_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id")
);

CREATE TABLE "FavoriteLists" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer,
    "AnonId" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_FavoriteLists" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_FavoriteLists_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id")
);

CREATE TABLE "PasswordResetTokens" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "TokenHash" text NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UsedAt" timestamp with time zone,
    CONSTRAINT "PK_PasswordResetTokens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PasswordResetTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "SavedCards" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "CardUserKey" text NOT NULL,
    "CardToken" text NOT NULL,
    "Brand" text NOT NULL,
    "Last4" text NOT NULL,
    "Holder" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_SavedCards" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SavedCards_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Orders" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrderId" integer NOT NULL,
    "UserId" integer,
    "AddressId" integer,
    "AnonId" text,
    "BuyerName" character varying(256),
    "BuyerEmail" character varying(256),
    "BuyerPhone" character varying(32),
    "ShippingAddressText" character varying(512),
    "ShippingCity" character varying(128),
    "ShippingState" character varying(128),
    "ShippingNeighbourhood" character varying(256),
    "Status" text,
    "OrderDate" timestamp with time zone NOT NULL,
    "TotalAmount" numeric NOT NULL,
    CONSTRAINT "PK_Orders" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Orders_Addresses_AddressId" FOREIGN KEY ("AddressId") REFERENCES "Addresses" ("Id"),
    CONSTRAINT "FK_Orders_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id")
);

CREATE TABLE "CartItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CartId" integer NOT NULL,
    "ProductId" integer NOT NULL,
    "Quantity" integer NOT NULL,
    "UnitPrice" numeric NOT NULL,
    CONSTRAINT "PK_CartItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CartItems_Carts_CartId" FOREIGN KEY ("CartId") REFERENCES "Carts" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CartItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
);

CREATE TABLE "FavoriteListItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FavoriteId" integer NOT NULL,
    "ProductId" integer NOT NULL,
    CONSTRAINT "PK_FavoriteListItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_FavoriteListItems_FavoriteLists_FavoriteId" FOREIGN KEY ("FavoriteId") REFERENCES "FavoriteLists" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_FavoriteListItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
);

CREATE TABLE "OrderItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrderId" integer NOT NULL,
    "ProductId" integer NOT NULL,
    "Quantity" integer NOT NULL,
    "UnitPrice" numeric NOT NULL,
    CONSTRAINT "PK_OrderItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OrderItems_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_OrderItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
);

CREATE TABLE "PaymentTransactions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrderId" integer NOT NULL,
    "Amount" numeric NOT NULL,
    "TransactionDate" timestamp with time zone NOT NULL,
    "PaymentMethod" text,
    "TransactionId" text,
    CONSTRAINT "PK_PaymentTransactions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PaymentTransactions_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Shipments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrderId" integer NOT NULL,
    "ShippedDate" timestamp with time zone NOT NULL,
    "TrackingNumber" text NOT NULL,
    "Carrier" text NOT NULL,
    CONSTRAINT "PK_Shipments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Shipments_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Addresses_UserId" ON "Addresses" ("UserId");

CREATE UNIQUE INDEX "IX_CartItems_CartId_ProductId" ON "CartItems" ("CartId", "ProductId");

CREATE INDEX "IX_CartItems_ProductId" ON "CartItems" ("ProductId");

CREATE UNIQUE INDEX "IX_Carts_AnonId" ON "Carts" ("AnonId") WHERE "AnonId" IS NOT NULL;

CREATE UNIQUE INDEX "IX_Carts_UserId" ON "Carts" ("UserId") WHERE "UserId" IS NOT NULL;

CREATE INDEX "IX_FavoriteListItems_FavoriteId" ON "FavoriteListItems" ("FavoriteId");

CREATE INDEX "IX_FavoriteListItems_ProductId" ON "FavoriteListItems" ("ProductId");

CREATE INDEX "IX_FavoriteLists_UserId" ON "FavoriteLists" ("UserId");

CREATE UNIQUE INDEX "IX_Inventories_ProductId" ON "Inventories" ("ProductId");

CREATE INDEX "IX_OrderItems_OrderId" ON "OrderItems" ("OrderId");

CREATE INDEX "IX_OrderItems_ProductId" ON "OrderItems" ("ProductId");

CREATE INDEX "IX_Orders_AddressId" ON "Orders" ("AddressId");

CREATE INDEX "IX_Orders_UserId" ON "Orders" ("UserId");

CREATE UNIQUE INDEX "IX_PasswordResetTokens_TokenHash" ON "PasswordResetTokens" ("TokenHash");

CREATE INDEX "IX_PasswordResetTokens_UserId" ON "PasswordResetTokens" ("UserId");

CREATE INDEX "IX_PaymentTransactions_OrderId" ON "PaymentTransactions" ("OrderId");

CREATE INDEX "IX_ProductCategories_CategoryId" ON "ProductCategories" ("CategoryId");

CREATE INDEX "IX_ProductCategories_ProductId" ON "ProductCategories" ("ProductId");

CREATE INDEX "IX_ProductDiscounts_ProductId" ON "ProductDiscounts" ("ProductId");

CREATE UNIQUE INDEX "IX_Products_Slug" ON "Products" ("Slug");

CREATE UNIQUE INDEX "IX_SavedCards_UserId_CardToken" ON "SavedCards" ("UserId", "CardToken");

CREATE UNIQUE INDEX "IX_Shipments_OrderId" ON "Shipments" ("OrderId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260507123417_InitialCreate', '9.0.8');

COMMIT;

